version: '3.8'

services:
  updown-frontend:
    container_name: updown-frontend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    restart: unless-stopped
    networks:
      - updown-net

networks:
  updown-net:
    external: true