name: Deploy Frontend to GCP

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Build & Deploy via SSH
    runs-on: ubuntu-latest

    steps:
      - name: Connect to GCP VM and deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.GCP_HOST }}
          username: ${{ secrets.GCP_USER }}
          key: ${{ secrets.GCP_SSH_KEY }}

          script: |
            cd ~/updown-frontend
            
            git pull origin master
            
            docker compose up -d --build